services:
  python:
    build: .
    container_name: cont-python
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:latest
    container_name: cont-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: employee_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
